/*
 * Do not edit: automatically generated by mkavrintel.pl
 *
 * hw_boot_sections.h
 *
 * Defines numbers of boot sections and size of smallest one, if any
 * Email the meta-author regarding errors/omissions in this file
 *
 * Published under GNU General Public License, version 3 (GPL-3.0)
 * Meta-author Stefan Rueger <stefan.rueger@urclocks.com>
 *
 * v 1.0
 * 21.02.2023
 *
 */

#ifndef HW_BOOT_SECTIONS_H
#define HW_BOOT_SECTIONS_H

#if 0

Defines the following constants:

HW_N_BOOT_SECTIONS, which can be
 -1 Unkown whether part has hardware boot sections or not (eg, missing ATDFs)
  0 Part does not support hardware boot sections
  1 For, eg, XMEGAs that have one boot section in top flash
  1 For modern (AVR8X) parts that have a variable sized boot section in bottom flash
  4 There are four sizes of boot sections in top flash: 2^i min_size with i in 0..3

HW_MIN_BOOTSIZE, which can be
   -1 Unkown whether part has hardware boot section support or not
    0 Part does not support hardware boot sections
  <n> Minimum size (eg, XMEGA only have one size but other sizes vary)

HW_BLSTART0, which can be
      -1 When the part does not support hardware boot sections or it is not known is does
  <addr> Address of start of *smallest* possible bootloader


#elif defined(__AVR_ATmega256RFR2__) || defined(__AVR_ATmega2560__) || \
  defined(__AVR_ATmega2561__) || defined(__AVR_ATmega2564RFR2__)

#define HW_N_BOOT_SECTIONS    4
#define HW_MIN_BOOTSIZE    1024
#define HW_BLSTART0     0x3fbff

#elif defined(__AVR_ATmega128__) || defined(__AVR_ATmega128A__) || \
  defined(__AVR_ATmega128RFA1__) || defined(__AVR_ATmega128RFR2__) || \
  defined(__AVR_ATmega1280__) || defined(__AVR_ATmega1281__) || defined(__AVR_ATmega1284__) || \
  defined(__AVR_ATmega1284P__) || defined(__AVR_ATmega1284RFR2__) || \
  defined(__AVR_AT90CAN128__) || defined(__AVR_AT90USB1286__) || defined(__AVR_AT90USB1287__)

#define HW_N_BOOT_SECTIONS    4
#define HW_MIN_BOOTSIZE    1024
#define HW_BLSTART0     0x1fbff

#elif defined(__AVR_AT90SCR100__)

#define HW_N_BOOT_SECTIONS    4
#define HW_MIN_BOOTSIZE     512
#define HW_BLSTART0      0xfdff

#elif defined(__AVR_ATmega64__) || defined(__AVR_ATmega64A__) || defined(__AVR_ATmega64HVE__) || \
  defined(__AVR_ATmega64C1__) || defined(__AVR_ATmega64M1__) || defined(__AVR_ATmega64HVE2__) || \
  defined(__AVR_ATmega64RFR2__) || defined(__AVR_ATmega640__) || defined(__AVR_ATmega644__) || \
  defined(__AVR_ATmega644A__) || defined(__AVR_ATmega644P__) || defined(__AVR_ATmega644PA__) || \
  defined(__AVR_ATmega644RFR2__) || defined(__AVR_ATmega645__) || defined(__AVR_ATmega645A__) || \
  defined(__AVR_ATmega645P__) || defined(__AVR_ATmega649__) || defined(__AVR_ATmega649A__) || \
  defined(__AVR_ATmega649P__) || defined(__AVR_ATmega6450__) || defined(__AVR_ATmega6450A__) || \
  defined(__AVR_ATmega6450P__) || defined(__AVR_ATmega6490__) || defined(__AVR_ATmega6490A__) || \
  defined(__AVR_ATmega6490P__) || defined(__AVR_AT90CAN64__) || defined(__AVR_AT90USB646__) || \
  defined(__AVR_AT90USB647__)

#define HW_N_BOOT_SECTIONS    4
#define HW_MIN_BOOTSIZE    1024
#define HW_BLSTART0      0xfbff

#elif defined(__AVR_ATmega406__)

#define HW_N_BOOT_SECTIONS    4
#define HW_MIN_BOOTSIZE     512
#define HW_BLSTART0      0x9dff

#elif defined(__AVR_ATmega32__) || defined(__AVR_ATmega32A__) || defined(__AVR_ATmega32HVB__) || \
  defined(__AVR_ATmega32HVBrevB__) || defined(__AVR_ATmega32C1__) || \
  defined(__AVR_ATmega32M1__) || defined(__AVR_ATmega32U2__) || defined(__AVR_ATmega32U4__) || \
  defined(__AVR_ATmega32U6__) || defined(__AVR_ATmega323__) || defined(__AVR_ATmega324A__) || \
  defined(__AVR_ATmega324P__) || defined(__AVR_ATmega324PA__) || defined(__AVR_ATmega324PB__) || \
  defined(__AVR_ATmega325__) || defined(__AVR_ATmega325A__) || defined(__AVR_ATmega325P__) || \
  defined(__AVR_ATmega325PA__) || defined(__AVR_ATmega328__) || defined(__AVR_ATmega328P__) || \
  defined(__AVR_ATmega328PB__) || defined(__AVR_ATmega329__) || defined(__AVR_ATmega329A__) || \
  defined(__AVR_ATmega329P__) || defined(__AVR_ATmega329PA__) || defined(__AVR_ATmega3250__) || \
  defined(__AVR_ATmega3250A__) || defined(__AVR_ATmega3250P__) || \
  defined(__AVR_ATmega3250PA__) || defined(__AVR_ATmega3290__) || defined(__AVR_ATmega3290A__) || \
  defined(__AVR_ATmega3290P__) || defined(__AVR_ATmega3290PA__) || defined(__AVR_ATA6614Q__)

#define HW_N_BOOT_SECTIONS    4
#define HW_MIN_BOOTSIZE     512
#define HW_BLSTART0      0x7dff

#elif defined(__AVR_AT90CAN32__)

#define HW_N_BOOT_SECTIONS    4
#define HW_MIN_BOOTSIZE    1024
#define HW_BLSTART0      0x7bff

#elif defined(__AVR_ATmega16__) || defined(__AVR_ATmega16A__) || defined(__AVR_ATmega162__) || \
  defined(__AVR_ATmega163__) || defined(__AVR_ATmega164A__) || defined(__AVR_ATmega164P__) || \
  defined(__AVR_ATmega164PA__) || defined(__AVR_ATmega165__) || defined(__AVR_ATmega165A__) || \
  defined(__AVR_ATmega165P__) || defined(__AVR_ATmega165PA__) || defined(__AVR_ATmega168__) || \
  defined(__AVR_ATmega168A__) || defined(__AVR_ATmega168P__) || defined(__AVR_ATmega168PA__) || \
  defined(__AVR_ATmega168PB__) || defined(__AVR_ATmega169__) || defined(__AVR_ATmega169A__) || \
  defined(__AVR_ATmega169P__) || defined(__AVR_ATmega169PA__) || defined(__AVR_AT90PWM161__) || \
  defined(__AVR_ATA6613C__)

#define HW_N_BOOT_SECTIONS    4
#define HW_MIN_BOOTSIZE     256
#define HW_BLSTART0      0x3eff

#elif defined(__AVR_ATmega16HVB__) || defined(__AVR_ATmega16HVBrevB__) || \
  defined(__AVR_ATmega16M1__) || defined(__AVR_ATmega16U2__) || defined(__AVR_ATmega16U4__) || \
  defined(__AVR_AT90USB162__) || defined(__AVR_AT90PWM216__) || defined(__AVR_AT90PWM316__)

#define HW_N_BOOT_SECTIONS    4
#define HW_MIN_BOOTSIZE     512
#define HW_BLSTART0      0x3dff

#elif defined(__AVR_ATtiny828__) || defined(__AVR_ATtiny828R__) || defined(__AVR_ATmega8__) || \
  defined(__AVR_ATmega8A__) || defined(__AVR_ATmega88__) || defined(__AVR_ATmega88A__) || \
  defined(__AVR_ATmega88P__) || defined(__AVR_ATmega88PA__) || defined(__AVR_ATmega88PB__) || \
  defined(__AVR_ATmega8515__) || defined(__AVR_ATmega8535__) || defined(__AVR_AT90PWM1__) || \
  defined(__AVR_AT90PWM2__) || defined(__AVR_AT90PWM2B__) || defined(__AVR_AT90PWM3__) || \
  defined(__AVR_AT90PWM3B__) || defined(__AVR_AT90PWM81__) || defined(__AVR_ATA6285__) || \
  defined(__AVR_ATA6286__) || defined(__AVR_ATA6289__) || defined(__AVR_ATA6612C__)

#define HW_N_BOOT_SECTIONS    4
#define HW_MIN_BOOTSIZE     256
#define HW_BLSTART0      0x1eff

#elif defined(__AVR_ATmega8U2__) || defined(__AVR_AT90USB82__)

#define HW_N_BOOT_SECTIONS    4
#define HW_MIN_BOOTSIZE     512
#define HW_BLSTART0      0x1dff

#elif defined(__AVR_ATxmega384C3__) || defined(__AVR_ATxmega384D3__)

#define HW_N_BOOT_SECTIONS    1
#define HW_MIN_BOOTSIZE    8192
#define HW_BLSTART0     0x5ffff

#elif defined(__AVR_ATxmega256A3__) || defined(__AVR_ATxmega256A3B__) || \
  defined(__AVR_ATxmega256A3BU__) || defined(__AVR_ATxmega256A3U__) || \
  defined(__AVR_ATxmega256C3__) || defined(__AVR_ATxmega256D3__)

#define HW_N_BOOT_SECTIONS    1
#define HW_MIN_BOOTSIZE    8192
#define HW_BLSTART0     0x3ffff

#elif defined(__AVR_ATxmega192A3__) || defined(__AVR_ATxmega192A3U__) || \
  defined(__AVR_ATxmega192C3__) || defined(__AVR_ATxmega192D3__)

#define HW_N_BOOT_SECTIONS    1
#define HW_MIN_BOOTSIZE    8192
#define HW_BLSTART0     0x2ffff

#elif defined(__AVR_ATxmega128A1__) || defined(__AVR_ATxmega128A1revD__) || \
  defined(__AVR_ATxmega128A1U__) || defined(__AVR_ATxmega128B1__) || \
  defined(__AVR_ATxmega128A3__) || defined(__AVR_ATxmega128A3U__) || \
  defined(__AVR_ATxmega128B3__) || defined(__AVR_ATxmega128C3__) || \
  defined(__AVR_ATxmega128D3__) || defined(__AVR_ATxmega128A4U__) || \
  defined(__AVR_ATxmega128D4__)

#define HW_N_BOOT_SECTIONS    1
#define HW_MIN_BOOTSIZE    8192
#define HW_BLSTART0     0x1ffff

#elif defined(__AVR_ATxmega64A1__) || defined(__AVR_ATxmega64A1U__) || \
  defined(__AVR_ATxmega64B1__) || defined(__AVR_ATxmega64A3__) || \
  defined(__AVR_ATxmega64A3U__) || defined(__AVR_ATxmega64B3__) || \
  defined(__AVR_ATxmega64C3__) || defined(__AVR_ATxmega64D3__) || \
  defined(__AVR_ATxmega64A4U__) || defined(__AVR_ATxmega64D4__)

#define HW_N_BOOT_SECTIONS    1
#define HW_MIN_BOOTSIZE    4096
#define HW_BLSTART0      0xffff

#elif defined(__AVR_ATA5782__) || defined(__AVR_ATA5831__) || defined(__AVR_ATA8210__) || \
  defined(__AVR_ATA8510__)

#define HW_N_BOOT_SECTIONS    1
#define HW_MIN_BOOTSIZE   20480
#define HW_BLSTART0      0x7fff

#elif defined(__AVR_ATxmega32C3__) || defined(__AVR_ATxmega32D3__) || \
  defined(__AVR_ATxmega32A4__) || defined(__AVR_ATxmega32A4U__) || \
  defined(__AVR_ATxmega32C4__) || defined(__AVR_ATxmega32D4__) || defined(__AVR_ATxmega32E5__)

#define HW_N_BOOT_SECTIONS    1
#define HW_MIN_BOOTSIZE    4096
#define HW_BLSTART0      0x7fff

#elif defined(__AVR_ATxmega16A4__) || defined(__AVR_ATxmega16A4U__) || \
  defined(__AVR_ATxmega16C4__) || defined(__AVR_ATxmega16D4__) || defined(__AVR_ATxmega16E5__)

#define HW_N_BOOT_SECTIONS    1
#define HW_MIN_BOOTSIZE    4096
#define HW_BLSTART0      0x3fff

#elif defined(__AVR_ATmega161__)

#define HW_N_BOOT_SECTIONS    1
#define HW_MIN_BOOTSIZE    1024
#define HW_BLSTART0      0x3bff

#elif defined(__AVR_ATA5790__) || defined(__AVR_ATA5790N__) || defined(__AVR_ATA5791__)

#define HW_N_BOOT_SECTIONS    1
#define HW_MIN_BOOTSIZE    2048
#define HW_BLSTART0      0x37ff

#elif defined(__AVR_ATxmega8E5__)

#define HW_N_BOOT_SECTIONS    1
#define HW_MIN_BOOTSIZE    2048
#define HW_BLSTART0      0x1fff

#elif defined(__AVR_ATA5795__)

#define HW_N_BOOT_SECTIONS    1
#define HW_MIN_BOOTSIZE    2048
#define HW_BLSTART0      0x17ff

#elif defined(__AVR_AVR8EA28__) || defined(__AVR_AVR8EA32__) || defined(__AVR_AVR16DD14__) || \
  defined(__AVR_AVR16DD20__) || defined(__AVR_AVR16DD28__) || defined(__AVR_AVR16EA28__) || \
  defined(__AVR_AVR16DD32__) || defined(__AVR_AVR16EA32__) || defined(__AVR_AVR16EA48__) || \
  defined(__AVR_AVR32DD14__) || defined(__AVR_AVR32DD20__) || defined(__AVR_AVR32DA28__) || \
  defined(__AVR_AVR32DB28__) || defined(__AVR_AVR32DD28__) || defined(__AVR_AVR32EA28__) || \
  defined(__AVR_AVR32DA32__) || defined(__AVR_AVR32DB32__) || defined(__AVR_AVR32DD32__) || \
  defined(__AVR_AVR32EA32__) || defined(__AVR_AVR32DA48__) || defined(__AVR_AVR32DB48__) || \
  defined(__AVR_AVR32EA48__) || defined(__AVR_AVR64DD14__) || defined(__AVR_AVR64DD20__) || \
  defined(__AVR_AVR64DA28__) || defined(__AVR_AVR64DB28__) || defined(__AVR_AVR64DD28__) || \
  defined(__AVR_AVR64EA28__) || defined(__AVR_AVR64DA32__) || defined(__AVR_AVR64DB32__) || \
  defined(__AVR_AVR64DD32__) || defined(__AVR_AVR64EA32__) || defined(__AVR_AVR64DA48__) || \
  defined(__AVR_AVR64DB48__) || defined(__AVR_AVR64EA48__) || defined(__AVR_AVR64DA64__) || \
  defined(__AVR_AVR64DB64__) || defined(__AVR_AVR128DA28__) || defined(__AVR_AVR128DB28__) || \
  defined(__AVR_AVR128DA32__) || defined(__AVR_AVR128DB32__) || defined(__AVR_AVR128DA48__) || \
  defined(__AVR_AVR128DB48__) || defined(__AVR_AVR128DA64__) || defined(__AVR_AVR128DB64__)

#define HW_N_BOOT_SECTIONS    1
#define HW_MIN_BOOTSIZE     512
#define HW_BLSTART0           0

#elif defined(__AVR_ATtiny202__) || defined(__AVR_ATtiny204__) || defined(__AVR_ATtiny212__) || \
  defined(__AVR_ATtiny214__) || defined(__AVR_ATtiny402__) || defined(__AVR_ATtiny404__) || \
  defined(__AVR_ATtiny406__) || defined(__AVR_ATtiny412__) || defined(__AVR_ATtiny414__) || \
  defined(__AVR_ATtiny416__) || defined(__AVR_ATtiny416auto__) || defined(__AVR_ATtiny417__) || \
  defined(__AVR_ATtiny424__) || defined(__AVR_ATtiny426__) || defined(__AVR_ATtiny427__) || \
  defined(__AVR_ATtiny804__) || defined(__AVR_ATtiny806__) || defined(__AVR_ATtiny807__) || \
  defined(__AVR_ATtiny814__) || defined(__AVR_ATtiny816__) || defined(__AVR_ATtiny817__) || \
  defined(__AVR_ATtiny824__) || defined(__AVR_ATtiny826__) || defined(__AVR_ATtiny827__) || \
  defined(__AVR_ATtiny1604__) || defined(__AVR_ATtiny1606__) || defined(__AVR_ATtiny1607__) || \
  defined(__AVR_ATtiny1614__) || defined(__AVR_ATtiny1616__) || defined(__AVR_ATtiny1617__) || \
  defined(__AVR_ATtiny1624__) || defined(__AVR_ATtiny1626__) || defined(__AVR_ATtiny1627__) || \
  defined(__AVR_ATtiny3214__) || defined(__AVR_ATtiny3216__) || defined(__AVR_ATtiny3217__) || \
  defined(__AVR_ATtiny3224__) || defined(__AVR_ATtiny3226__) || defined(__AVR_ATtiny3227__) || \
  defined(__AVR_ATmega808__) || defined(__AVR_ATmega809__) || defined(__AVR_ATmega1608__) || \
  defined(__AVR_ATmega1609__) || defined(__AVR_ATmega3208__) || defined(__AVR_ATmega3209__) || \
  defined(__AVR_ATmega4808__) || defined(__AVR_ATmega4809__)

#define HW_N_BOOT_SECTIONS    1
#define HW_MIN_BOOTSIZE     256
#define HW_BLSTART0           0

#elif defined(__AVR_ATtiny4__) || defined(__AVR_ATtiny5__) || defined(__AVR_ATtiny9__) || \
  defined(__AVR_ATtiny10__) || defined(__AVR_ATtiny20__) || defined(__AVR_ATtiny40__) || \
  defined(__AVR_ATtiny102__) || defined(__AVR_ATtiny104__) || defined(__AVR_ATtiny11__) || \
  defined(__AVR_ATtiny12__) || defined(__AVR_ATtiny13__) || defined(__AVR_ATtiny13A__) || \
  defined(__AVR_ATtiny15__) || defined(__AVR_ATtiny22__) || defined(__AVR_ATtiny24__) || \
  defined(__AVR_ATtiny24A__) || defined(__AVR_ATtiny25__) || defined(__AVR_ATtiny26__) || \
  defined(__AVR_ATtiny28__) || defined(__AVR_ATtiny43U__) || defined(__AVR_ATtiny44__) || \
  defined(__AVR_ATtiny44A__) || defined(__AVR_ATtiny45__) || defined(__AVR_ATtiny48__) || \
  defined(__AVR_ATtiny84__) || defined(__AVR_ATtiny84A__) || defined(__AVR_ATtiny85__) || \
  defined(__AVR_ATtiny87__) || defined(__AVR_ATtiny88__) || defined(__AVR_ATtiny167__) || \
  defined(__AVR_ATtiny261__) || defined(__AVR_ATtiny261A__) || defined(__AVR_ATtiny441__) || \
  defined(__AVR_ATtiny461__) || defined(__AVR_ATtiny461A__) || defined(__AVR_ATtiny841__) || \
  defined(__AVR_ATtiny861__) || defined(__AVR_ATtiny861A__) || defined(__AVR_ATtiny1634__) || \
  defined(__AVR_ATtiny1634R__) || defined(__AVR_ATtiny2313__) || defined(__AVR_ATtiny2313A__) || \
  defined(__AVR_ATtiny4313__) || defined(__AVR_ATmega8HVA__) || defined(__AVR_ATmega16HVA__) || \
  defined(__AVR_ATmega48__) || defined(__AVR_ATmega48A__) || defined(__AVR_ATmega48P__) || \
  defined(__AVR_ATmega48PA__) || defined(__AVR_ATmega48PB__) || defined(__AVR_ATmega103__) || \
  defined(__AVR_AT90S1200__) || defined(__AVR_AT90S2313__) || defined(__AVR_AT90S2323__) || \
  defined(__AVR_AT90S2333__) || defined(__AVR_AT90S2343__) || defined(__AVR_AT90S4414__) || \
  defined(__AVR_AT90S4433__) || defined(__AVR_AT90S4434__) || defined(__AVR_AT90S8515__) || \
  defined(__AVR_AT90S8535__) || defined(__AVR_ATA5272__) || defined(__AVR_ATA5505__) || \
  defined(__AVR_ATA5700M322__) || defined(__AVR_ATA5702M322__) || defined(__AVR_ATA5781__) || \
  defined(__AVR_ATA5783__) || defined(__AVR_ATA5787__) || defined(__AVR_ATA5832__) || \
  defined(__AVR_ATA5833__) || defined(__AVR_ATA5835__) || defined(__AVR_ATA6616C__) || \
  defined(__AVR_ATA6617C__) || defined(__AVR_ATA8215__) || defined(__AVR_ATA8515__) || \
  defined(__AVR_ATA664251__)

#define HW_N_BOOT_SECTIONS    0
#define HW_MIN_BOOTSIZE       0
#define HW_BLSTART0          -1

#elif defined(__AVR_ATmega16HVA2__) || defined(__AVR_AT43USB320__) || \
  defined(__AVR_AT43USB355__) || defined(__AVR_AT76C711__) || defined(__AVR_AT86RF401__) || \
  defined(__AVR_AT90C8534__) || defined(__AVR_AT94K__) || defined(__AVR_M3000__) || \
  defined(__AVR_LGT8F88P__) || defined(__AVR_LGT8F168P__) || defined(__AVR_LGT8F328P__) || \
  defined(__AVR_ATxmega64A4__) || defined(__AVR_ATxmega128A4__) || \
  defined(__AVR_ATxmega192A1__) || defined(__AVR_ATxmega256A1__)

#define HW_N_BOOT_SECTIONS   -1
#define HW_MIN_BOOTSIZE      -1
#define HW_BLSTART0          -1

#else
#define UR_NBOOTS            -1
#define UR_MIN_BOOTSIZE      -1
#define HW_BLSTART0          -1

#endif

#endif
